### ISSUE TITLE
Update template files to utilize namespaces

### ISSUE THREAD

**Issue by cjg89** [UCF/CM-WP-Child-Theme-Template#3]
**Description**

See title.

**Why it's Important**

Namespaces are cleaner than adding prefixes to function names.

**Alternatives**

**Possible Implementation**

See FinAid Child Theme as an example.  Namespace definitions should be added to functions.php, includes/config.php and includes/meta.php

**Additional context**

**Comment by cadie** [comment]
Merged into master. #5
