### ISSUE TITLE
Add theme dir path to included files in functions.php template

### ISSUE THREAD

**Issue by cjg89** [UCF/CM-WP-Child-Theme-Template#4]
**Description**

See title

**Why it's Important**

Avoid issues with relative path includes.

**Alternatives**

**Possible Implementation**

See FinAid Child Theme as an example.  https://github.com/UCF/FinAid-Child-Theme/blob/master/functions.php#L4-L13

**Additional context**

**Comment by cadie** [comment]
Merged into master. #5
